# Generated by Django 6.0.3 on 2026-04-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'media_buyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name="Прив'язаний баєр"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('media_buyer', 'Медіабайєр'), ('creative', 'Креативник')], default='media_buyer', max_length=20),
        ),
    ]
