# Generated by Django 6.0.3 on 2026-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_supervisor_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_changed_password',
            field=models.BooleanField(default=False, verbose_name='Пароль змінено'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_requested',
            field=models.BooleanField(default=False, verbose_name='Запит на скидання пароля'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тимчасовий пароль'),
        ),
    ]
