# Generated by Django 6.0.3 on 2026-04-17 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_has_changed_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=255, unique=True, verbose_name='TikTok OpenID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я в TikTok")),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
