# Generated by Django 6.0.3 on 2026-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tiktokintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokintegration',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tiktokintegration',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokintegration',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
