# Generated by Django 6.0.3 on 2026-04-17 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_tiktokintegration_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_id', models.CharField(max_length=100, unique=True, verbose_name='Advertiser ID')),
                ('advertiser_name', models.CharField(max_length=255, verbose_name='Назва кабінету')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='ENABLE', max_length=50)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ad_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Баєр')),
                ('main_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_ad_accounts', to='users.tiktokintegration')),
            ],
            options={
                'verbose_name': 'Рекламний акаунт TikTok',
                'verbose_name_plural': 'Рекламні акаунти TikTok',
            },
        ),
    ]
