# Generated by Django 6.0.3 on 2026-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tiktokadaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TikTokAdAccount',
        ),
    ]
