# Generated by Django 6.0.3 on 2026-04-17 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_has_changed_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_team_lead',
            field=models.BooleanField(default=False, verbose_name='Статус Тімліда'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва команди')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team', to=settings.AUTH_USER_MODEL, verbose_name='Тімлід')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.team', verbose_name='Команда'),
        ),
    ]
