# Generated by Django 6.0.3 on 2026-04-17 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_supervisor_customuser_is_team_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_creatives',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'creative'}, related_name='assigned_buyers', to=settings.AUTH_USER_MODEL, verbose_name='Призначені креативники'),
        ),
    ]
