# Generated by Django 6.0.3 on 2026-04-17 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_assigned_creatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokintegration',
            name='allowed_buyers',
            field=models.ManyToManyField(blank=True, related_name='shared_bc_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Дозволені баєри'),
        ),
    ]
