# Generated by Django 6.0.3 on 2026-03-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва кампанії')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('PAUSED', 'На паузі'), ('COMPLETED', 'Завершена')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет ($)')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Витрачено ($)')),
                ('impressions', models.IntegerField(default=0, verbose_name='Покази')),
                ('clicks', models.IntegerField(default=0, verbose_name='Кліки')),
                ('conversions', models.IntegerField(default=0, verbose_name='Конверсії')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Власник (Медіабайєр)')),
            ],
            options={
                'verbose_name': 'Рекламна кампанія',
                'verbose_name_plural': 'Рекламні кампанії',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва креативу')),
                ('duration', models.IntegerField(help_text='Наприклад: 15', verbose_name='Тривалість (сек)')),
                ('hook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хук (гачок)')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Витрачено на креатив ($)')),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ROI (%)')),
                ('is_burning_out', models.BooleanField(default=False, verbose_name='Ознаки вигорання (Ad Fatigue)')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='analytics.campaign', verbose_name='Кампанія')),
            ],
            options={
                'verbose_name': 'Креатив',
                'verbose_name_plural': 'Креативи',
            },
        ),
    ]
