# Generated by Django 6.0.3 on 2026-04-17 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0007_alter_customuser_has_changed_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreative',
            name='duration',
            field=models.IntegerField(verbose_name='Тривалість (сек)'),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='hook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хук'),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='is_burning_out',
            field=models.BooleanField(default=False, verbose_name='Ознаки вигорання'),
        ),
        migrations.CreateModel(
            name='TikTokAdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_id', models.CharField(max_length=100, unique=True, verbose_name='Advertiser ID')),
                ('advertiser_name', models.CharField(max_length=255, verbose_name='Назва кабінету')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='ENABLE', max_length=50)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ad_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Баєр')),
                ('main_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_ad_accounts', to='users.tiktokintegration')),
            ],
            options={
                'verbose_name': 'Рекламний акаунт TikTok',
                'verbose_name_plural': 'Рекламні акаунти TikTok',
            },
        ),
    ]
