# Generated by Django 6.0.3 on 2026-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_adcreative_duration_alter_adcreative_hook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pause_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата паузи'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старту'),
        ),
    ]
