# Generated by Django 6.0.3 on 2026-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_campaign_end_date_campaign_pause_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='geo',
            field=models.CharField(choices=[('US', 'USA'), ('GB', 'UK'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('UA', 'Ukraine'), ('PL', 'Poland'), ('BR', 'Brazil'), ('MX', 'Mexico')], default='US', max_length=5, verbose_name='ГЕО'),
        ),
    ]
