# Generated by Django 6.0.3 on 2026-03-11 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва ТЗ')),
                ('status', models.CharField(choices=[('DRAFT', 'Чернетка'), ('SENT', 'Відправлено кріейтору'), ('IN_PROGRESS', 'В роботі'), ('REVIEW', 'На перевірці'), ('COMPLETED', 'Готово')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('concept', models.TextField(help_text='Опишіть основну ідею відео', verbose_name='1. Загальна концепція')),
                ('hook', models.TextField(help_text='Що має зачепити увагу в перші 3 секунди?', verbose_name='2. Хук (Гачок)')),
                ('main_part', models.TextField(help_text='Сценарій та ключові тези', verbose_name='3. Основна частина')),
                ('cta', models.TextField(help_text='Що користувач має зробити в кінці?', verbose_name='4. Call to Action (Заклик до дії)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець (Кріейтор)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор (Медіабайєр)')),
                ('source_creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='analytics.adcreative', verbose_name='Джерело (Успішний креатив)')),
            ],
            options={
                'verbose_name': 'Технічне завдання (ТЗ)',
                'verbose_name_plural': 'Технічні завдання (ТЗ)',
            },
        ),
    ]
