# Generated by Django 6.0.3 on 2026-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='concept',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Загальне бачення відео', null=True, verbose_name='Загальний опис та побажання'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.CharField(choices=[('UP_TO_10', 'до 10 сек'), ('10_15', '10-15 сек'), ('15_30', '15-30 сек')], default='15_30', max_length=20, verbose_name='Тривалість'),
        ),
        migrations.AddField(
            model_name='task',
            name='geo',
            field=models.CharField(choices=[('US', 'United States (ENG)'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('UA', 'Ukraine'), ('PL', 'Poland'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('ID', 'Indonesia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates')], default='US', max_length=5, verbose_name='ГЕО'),
        ),
        migrations.AddField(
            model_name='task',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='task_references/', verbose_name='Прикріплений файл'),
        ),
        migrations.AddField(
            model_name='task',
            name='reference_links',
            field=models.TextField(blank=True, help_text='Вставте посилання з нового рядка', null=True, verbose_name='Посилання на референси'),
        ),
        migrations.AddField(
            model_name='task',
            name='voiceover_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для озвучки (VO)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cta',
            field=models.TextField(blank=True, help_text='Що користувач має зробити в кінці?', null=True, verbose_name='Call to Action'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hook',
            field=models.TextField(blank=True, help_text='Що має зачепити увагу в перші 3 секунди?', null=True, verbose_name='Хук (Гачок)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='main_part',
            field=models.TextField(blank=True, help_text='Сценарій та ключові тези', null=True, verbose_name='Основна частина'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Чернетка (TODO)'), ('SENT', 'Відправлено кріейтору'), ('IN_PROGRESS', 'В роботі'), ('REVIEW', 'На перевірці'), ('COMPLETED', 'Готово')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
    ]
