# Generated by Django 6.0.3 on 2026-04-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_concept_task_deadline_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reference_file',
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_references/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='Технічне завдання')),
            ],
            options={
                'verbose_name': 'Файл ТЗ',
                'verbose_name_plural': 'Файли ТЗ',
            },
        ),
    ]
