# Generated by Django 6.0.3 on 2026-04-16 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('tasks', '0003_remove_task_reference_file_taskfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskfile',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.CharField(choices=[('EASY', '🟢 Легка'), ('MEDIUM', '🟡 Середня'), ('HARD', '🔴 Складна')], default='MEDIUM', max_length=10, verbose_name='Складність'),
        ),
        migrations.AddField(
            model_name='task',
            name='needs_voiceover',
            field=models.BooleanField(default=False, verbose_name='Потрібна озвучка'),
        ),
        migrations.AddField(
            model_name='task',
            name='vo_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мова озвучки'),
        ),
        migrations.AddField(
            model_name='task',
            name='vo_voice',
            field=models.CharField(blank=True, choices=[('MALE', 'Чоловічий'), ('FEMALE', 'Жіночий')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='cta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(choices=[('UP_TO_10', 'до 10 сек'), ('10_15', '10-15 сек'), ('15_30', '15-30 сек')], default='15_30', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='geo',
            field=models.CharField(choices=[('US', 'United States (ENG)'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('UA', 'Ukraine'), ('PL', 'Poland'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('ID', 'Indonesia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SA', 'Saudi Arabia'), ('AE', 'UAE')], default='US', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='hook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='main_part',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reference_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.adcreative'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Чернетка'), ('SENT', 'Відправлено'), ('IN_PROGRESS', 'В роботі'), ('REVIEW', 'На перевірці'), ('COMPLETED', 'Готово')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='voiceover_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to='task_references/'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task'),
        ),
    ]
