# Generated by Django 6.0.3 on 2026-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_alter_taskfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.CharField(choices=[('EASY', '🟢 Легка'), ('MEDIUM', '🟡 Середня'), ('HARD', '🔴 Складна')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='needs_voiceover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='vo_language',
            field=models.CharField(blank=True, choices=[('UK', 'Українська'), ('EN_US', 'English (US)'), ('EN_UK', 'English (UK)'), ('PL', 'Polish'), ('DE', 'German'), ('ES', 'Spanish'), ('FR', 'French'), ('IT', 'Italian'), ('PT', 'Portuguese')], max_length=10, null=True),
        ),
    ]
