# Generated by Django 6.0.3 on 2026-04-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_complexity_alter_task_needs_voiceover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='buyer_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Правки від баєра'),
        ),
        migrations.AddField(
            model_name='task',
            name='creative_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар креативника (до результату)'),
        ),
        migrations.CreateModel(
            name='TaskResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_results/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_files', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Файл результату',
                'verbose_name_plural': 'Файли результатів',
            },
        ),
    ]
